# Generated by Django 4.1.7 on 2023-05-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_short_url_url_short_url_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url_slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
