# Generated by Django 4.1.7 on 2023-05-20 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_url_original_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.URLField(error_messages={'invalid': 'Geçerli bir URL girin'}, validators=[django.core.validators.URLValidator()]),
        ),
    ]
